### ISSUE TITLE
Bug #2

### ISSUE THREAD

**Issue by hotboykila2014** [gianghd/userscript#3]
[https://metruyenchu.com/truyen/my-nu-sung-vat-quan-doan/](https://metruyenchu.com/truyen/my-nu-sung-vat-quan-doan/)
Truyện này từ web cũ truyencv chuyển qua, id của link chương không nối tiếp nhau gây lỗi.
Ví dụ chương 1060 có id là 1049 nhưng chương tiếp theo lại có id là 1051, script tìm link 1050 chẳng thấy nên nó đứng im.

Web nuhiep.com đóng cửa dẹp tiệm rồi, bạn xóa code của nó đi nha.

**Comment by gianghd** [comment]
Cái này để suy nghĩ solution đã. Ta cũng chưa nghĩ ra được fix thế nào.

**Comment by hotboykila2014** [comment]
> Cái này để suy nghĩ solution đã. Ta cũng chưa nghĩ ra được fix thế nào.

Lỗi này rất là ít gặp, chỉ khi tải mấy truyện cũ mới bị thôi, không ảnh hưởng mấy nên cứ thong thả.
Với lại lỗi này có cách fix tạm, lúc tải bị đứng click chuột trái vào nút tải thì script sẽ xuất file epub ra luôn, F5 lại web rồi chuột phải vào nút tải sau đó nhập id chương kế tiếp vào là nó tải tiếp đoạn sau.Chỉ là đọc 1 truyện bằng nhiều file epub khác nhau hơi bất tiện thôi.

**Comment by mkbyme** [comment]
Solution có 2 cách
1. Thêm retry vào, đếm theo đầu chapter, nếu 1 chapter tải thất bại quá 5 lần thì bỏ qua.
2. Check reponse status code != 404 (NotFound) trả về thay vì force cứ lỗi là lại gọi getContent()
