### ISSUE TITLE
Lỗi tải truyện web metruyencv

### ISSUE THREAD

**Issue by DiepT2411** [gianghd/userscript#6]
https://metruyencv.com/truyen/tran-yeu-vien-bao-tang
chào ad, web metruyencv.com giờ giấu nội dung, tải 1 nửa và 1 nửa tải sau có mã hóa, có vài bộ chỉ chạy được tầm 50 - 200 chương đầu là có nội dung đầy đủ, còn những chương còn lại là chỉ có vài dòng nội dung đầu của chương.
thanks

**Comment by gianghd** [comment]
Có thể cho mình xin link truyện như vậy không?

**Comment by gianghd** [comment]
Có vẻ khó rồi.

**Comment by DiepT2411** [comment]
qua ngày thì cho tải thêm 1 ít chương , như hôm trước được 50 chương, hôm sau có thể 100 chương, mà vài bộ hơn 1k chương mình đợi 2 tuần rồi vẫn chưa qua đươc 300 chương
